"""add provisioning_status to published_containers

Revision ID: 4c0982e1e767
Revises: ddda213de40a
Create Date: 2026-07-22 18:43:13.895715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0982e1e767'
down_revision: Union[str, Sequence[str], None] = 'ddda213de40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_containers', sa.Column('provisioning_status', sa.String(length=50), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_containers', 'provisioning_status')
    # ### end Alembic commands ###
