"""alter table connections, add colunm connected_at

Revision ID: 4ded5136c6fe
Revises: e72de3f871fc
Create Date: 2026-07-23 12:26:33.394933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ded5136c6fe'
down_revision: Union[str, Sequence[str], None] = 'e72de3f871fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('connected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'connected_at')
    # ### end Alembic commands ###
