"""create_headscale_persistence_tables

Revision ID: ddda213de40a
Revises: b6a467e62fc5
Create Date: 2026-07-22 15:50:28.894145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddda213de40a'
down_revision: Union[str, Sequence[str], None] = 'b6a467e62fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headscale_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('headscale_user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id')
    )
    op.create_table('headscale_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('published_container_id', sa.String(length=36), nullable=True),
    sa.Column('headscale_node_id', sa.String(length=255), nullable=False),
    sa.Column('headscale_user_id', sa.String(length=36), nullable=False),
    sa.Column('machine_key', sa.String(length=255), nullable=True),
    sa.Column('node_key', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('given_name', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['headscale_user_id'], ['headscale_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_container_id'], ['published_containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headscale_preauth_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('headscale_user_id', sa.String(length=36), nullable=False),
    sa.Column('published_container_id', sa.String(length=36), nullable=True),
    sa.Column('headscale_key_id', sa.String(length=255), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('ephemeral', sa.Boolean(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['headscale_user_id'], ['headscale_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_container_id'], ['published_containers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('headscale_preauth_keys')
    op.drop_table('headscale_nodes')
    op.drop_table('headscale_users')
    # ### end Alembic commands ###
