"""alter table connections

Revision ID: e72de3f871fc
Revises: 4c0982e1e767
Create Date: 2026-07-23 11:37:00.156020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e72de3f871fc'
down_revision: Union[str, Sequence[str], None] = '4c0982e1e767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('headscale_preauth_key_id', sa.String(length=36), nullable=False))
    op.add_column('connections', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('connections', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'connections', 'headscale_preauth_keys', ['headscale_preauth_key_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('connections', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_column('connections', 'expires_at')
    op.drop_column('connections', 'status')
    op.drop_column('connections', 'headscale_preauth_key_id')
    # ### end Alembic commands ###
